/**
 * 数据与研究框架来源：《消费结构演进与新兴市场消费投资方向研究》
 * 消费支出结构：Euromonitor（文中图表 3-4）；核心指标表：Euromonitor，作者整理。
 */
window.EMC_DATA = {
  site: {
    title: { zh: "新兴市场消费观察", en: "Emerging Markets Consumption Observatory" },
    subtitle: {
      zh: "消费结构 · 国别比较 · 需求阶段",
      en: "Consumption structure · Cross-country comparison · Demand stages",
    },
    homeLead: {
      zh: "基于消费者支出（Consumer Expenditure）框架，观察 15 个新兴经济体「钱包」流向与需求阶段。地图按国界着色：灰色为研究范围外；选择下方支出类别可按该国在该分项上的占比着色。点击着色国家进入国别页。",
      en: "Using Consumer Expenditure as the organizing lens, this microsite profiles 15 emerging economies. The map uses country boundaries: grey is outside the study set; pick an expenditure category below to colour countries by that share. Click a shaded sample country to open its profile.",
    },
    mapOverviewLabel: { zh: "概览（研究样本）", en: "Overview (sample)" },
    mapCategoryLabel: { zh: "消费支出类别", en: "Expenditure categories" },
    mapLoading: { zh: "正在加载国界数据…", en: "Loading country boundaries…" },
    mapHint: {
      zh: "灰色区域不在 15 国研究样本内。着色国家可点击进入详情。",
      en: "Grey areas are outside the 15-country sample. Shaded countries are clickable.",
    },
  },
  globalSources: {
    zh: [
      "国家统计局 / 央行与财政部门发布的国民经济核算与住户调查（各国官方，更新频率因国而异）",
      "World Bank Open Data — https://data.worldbank.org/ （宏观经济与人口等公开序列）",
      "International Monetary Fund — https://www.imf.org/en/Data （国别报告与宏观数据）",
      "United Nations Data — https://data.un.org/",
      "Euromonitor International — 消费者支出结构等行业数据库（本研究引用；页面展示口径与文中图表一致，实时订阅数据需向提供商更新）",
    ],
    en: [
      "National statistical offices / central banks / ministries (national accounts & household surveys; refresh cadence varies by country)",
      "World Bank Open Data — https://data.worldbank.org/",
      "International Monetary Fund Data — https://www.imf.org/en/Data",
      "United Nations Data — https://data.un.org/",
      "Euromonitor International — industry database cited in the research for consumer expenditure shares (figures shown match the study; live subscription feeds require provider access)",
    ],
  },
  categories: [
    { key: "food", zh: "食品饮料", en: "Food & beverages" },
    { key: "clothing", zh: "服饰", en: "Clothing & footwear" },
    { key: "housing", zh: "房屋", en: "Housing" },
    { key: "transport", zh: "交通", en: "Transport" },
    { key: "householdComms", zh: "家居通信", en: "Household & communications" },
    { key: "health", zh: "医疗健康", en: "Health" },
    { key: "education", zh: "教育", en: "Education" },
    { key: "leisure", zh: "娱乐", en: "Leisure & recreation" },
    { key: "hotelsCatering", zh: "酒店餐饮", en: "Hotels & catering" },
    { key: "other", zh: "其他", en: "Other" },
  ],
  countries: [
    {
      slug: "indonesia",
      iso3: "IDN",
      coords: [-2.5, 118],
      name: { zh: "印度尼西亚", en: "Indonesia" },
      region: { zh: "东南亚", en: "Southeast Asia" },
      stage: { zh: "生存需求阶段", en: "Survival-stage demand" },
      metrics: {
        marketVolumeMmUsd: 765418,
        perCapitaGdpKUsd: 4.9,
        gdpGrowthPct: 3.6,
        populationK: 283488,
        consumerExpPerCapitaKUsd: 2.7,
        medianAge: 31.1,
        householdSize: 3.2,
        gini: 39.3,
        easeBiz: 73,
      },
      consumption: {
        food: 34,
        clothing: 3,
        housing: 10,
        transport: 17,
        householdComms: 7,
        health: 3,
        education: 4,
        leisure: 2,
        hotelsCatering: 10,
        other: 2,
      },
      narrative: {
        zh: "印尼为东南亚人口与经济体量最大的样本之一，处于发展初期与高增速通道；支出结构呈现显著的生存型特征，食品饮料占比领先，交通支出相对较高，反映城市化与流动的扩张期特征。年轻人口与大家庭规模为大众品类渗透提供基本面，同时营商环境边际约束需要在项目层面个案评估。",
        en: "Indonesia combines very large population scale with an early-stage, fast-growing consumer market. Spending skews survival-stage—food & beverages lead, while transport is comparatively elevated, consistent with urbanisation and mobility expansion. A young demographic and larger household sizes support mass-market penetration; doing-business frictions warrant case-by-case diligence.",
      },
      bullets: {
        zh: [
          "大市场、发展初期、增速相对较高（研究口径下的坐标分层）",
          "食品饮料与交通为结构性“高占比”方向",
          "年轻人口结构支撑普及率提升逻辑",
        ],
        en: [
          "Large market, early-stage profile with comparatively strong growth (study taxonomy)",
          "Food & beverages and transport stand out as high-share categories",
          "Youthful demographics support penetration-led themes",
        ],
      },
      links: [
        {
          zh: "世界银行｜印度尼西亚",
          en: "World Bank | Indonesia",
          url: "https://data.worldbank.org/country/indonesia",
        },
        {
          zh: "IMF｜国别页面",
          en: "IMF | Country Page",
          url: "https://www.imf.org/en/Countries/IDN",
        },
        {
          zh: "印尼中央统计局 BPS",
          en: "Statistics Indonesia (BPS)",
          url: "https://www.bps.go.id/",
        },
      ],
    },
    {
      slug: "vietnam",
      iso3: "VNM",
      coords: [14.06, 108.28],
      name: { zh: "越南", en: "Viet Nam" },
      region: { zh: "东南亚", en: "Southeast Asia" },
      stage: { zh: "生存需求阶段", en: "Survival-stage demand" },
      metrics: {
        marketVolumeMmUsd: 232272,
        perCapitaGdpKUsd: 4.7,
        gdpGrowthPct: 5.6,
        populationK: 100988,
        consumerExpPerCapitaKUsd: 2.3,
        medianAge: 33.9,
        householdSize: 3.6,
        gini: 42.0,
        easeBiz: 70,
      },
      consumption: {
        food: 35,
        clothing: 5,
        housing: 12,
        transport: 11,
        householdComms: 8,
        health: 4,
        education: 6,
        leisure: 1,
        hotelsCatering: 11,
        other: 6,
      },
      narrative: {
        zh: "越南在研究样本中增速领先，人均消费水平仍在抬升通道；支出结构以生存需求为主，食品饮料与教育占比相对突出。公立供给扩容滞后与私立教育扩张并存，使教育赛道在研究中被重点关注（需求侧与供给侧需联动评估）。",
        en: "Viet Nam stands out for rapid growth with per-capita spending still climbing. The basket remains survival-led—food & beverages is large and education share is comparatively notable. Private education themes sit alongside public-capacity constraints (balance demand signals with supply-side readiness).",
      },
      bullets: {
        zh: ["东南亚中高增速样本", "食品饮料 + 教育占比值得关注", "人口年轻、家庭规模适中"],
        en: ["High-growth ASEAN benchmark", "Food & beverages plus education shares matter", "Young population; moderate household size"],
      },
      links: [
        { zh: "世界银行｜越南", en: "World Bank | Viet Nam", url: "https://data.worldbank.org/country/vietnam" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/VNM" },
        { zh: "越南统计局 GSO", en: "General Statistics Office", url: "https://www.gso.gov.vn/en/home/" },
      ],
    },
    {
      slug: "thailand",
      iso3: "THA",
      coords: [15.87, 100.99],
      name: { zh: "泰国", en: "Thailand" },
      region: { zh: "东南亚", en: "Southeast Asia" },
      stage: { zh: "品质需求阶段（输入性因素显著）", en: "Quality-stage demand (tourism-driven nuances)" },
      metrics: {
        marketVolumeMmUsd: 329673,
        perCapitaGdpKUsd: 7.3,
        gdpGrowthPct: 0.7,
        populationK: 71668,
        consumerExpPerCapitaKUsd: 4.6,
        medianAge: 41.1,
        householdSize: 2.8,
        gini: 29.9,
        easeBiz: 21,
      },
      consumption: {
        food: 24,
        clothing: 3,
        housing: 9,
        transport: 11,
        householdComms: 5,
        health: 5,
        education: 1,
        leisure: 4,
        hotelsCatering: 22,
        other: 12,
      },
      narrative: {
        zh: "泰国人均发展水平与购买力高于印尼、越南，但宏观增速偏低；人口老龄化程度在研究样本中偏高。支出结构中酒店餐饮与其他可选消费占比较高，使其呈现“品质阶段”特征——研究特别提示输入性旅游消费可能抬高相关分项，解读时需避免简单线性外推到本土内生消费升级。",
        en: "Thailand is richer than several ASEAN peers but posts softer headline growth; median age is elevated versus peers. Hotels/catering and discretionary bundles are unusually large—consistent with inbound tourism—so “quality-stage” signals should be interpreted with care vs. domestically driven upgrading.",
      },
      bullets: {
        zh: ["中高收入门槛 + 低增速组合", "酒店餐饮占比显著（旅游因素）", "老龄化推高医疗与服务长期议题"],
        en: ["Upper-middle income with low growth", "Large hotels/catering share (tourism)", "Ageing lifts healthcare & services over time"],
      },
      links: [
        { zh: "世界银行｜泰国", en: "World Bank | Thailand", url: "https://data.worldbank.org/country/thailand" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/THA" },
        { zh: "泰国中央银行 BOT", en: "Bank of Thailand", url: "https://www.bot.or.th/English/Pages/index.aspx" },
      ],
    },
    {
      slug: "malaysia",
      iso3: "MYS",
      coords: [4.21, 101.98],
      name: { zh: "马来西亚", en: "Malaysia" },
      region: { zh: "东南亚", en: "Southeast Asia" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 265660,
        perCapitaGdpKUsd: 12.4,
        gdpGrowthPct: 3.2,
        populationK: 34059,
        consumerExpPerCapitaKUsd: 7.8,
        medianAge: 32.6,
        householdSize: 3.8,
        gini: 40.8,
        easeBiz: 12,
      },
      consumption: {
        food: 26,
        clothing: 3,
        housing: 15,
        transport: 13,
        householdComms: 14,
        health: 3,
        education: 2,
        leisure: 4,
        hotelsCatering: 10,
        other: 10,
      },
      narrative: {
        zh: "马来西亚在研究框架中更接近“发展成熟 + 中增速”，营商环境评分样本内领先。支出结构体现便利型特征：家居通信等模块占比抬升，反映家电、通讯与家庭场景消费的渗透深化，是从生存迈向便利阶段的典型组合之一。",
        en: "Malaysia sits closer to “mature market / medium growth” in the study frame and scores well on ease of doing business. Expenditure skews convenience-stage—household & communications is comparatively large, reflecting deeper penetration of connected homes and household durables.",
      },
      bullets: {
        zh: ["人均 GDP 与消费能力领先多数东盟样本", "家居通信占比高：便利型特征", "营商环境相对友好"],
        en: ["Higher GDP per capita vs many ASEAN peers", "Elevated household & communications: convenience-stage", "Comparatively friendly business climate"],
      },
      links: [
        { zh: "世界银行｜马来西亚", en: "World Bank | Malaysia", url: "https://data.worldbank.org/country/malaysia" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/MYS" },
        { zh: "马来西亚统计局 DOSM", en: "Department of Statistics Malaysia", url: "https://www.dosm.gov.my/" },
      ],
    },
    {
      slug: "uzbekistan",
      iso3: "UZB",
      coords: [41.38, 64.59],
      name: { zh: "乌兹别克斯坦", en: "Uzbekistan" },
      region: { zh: "中亚", en: "Central Asia" },
      stage: { zh: "生存需求阶段", en: "Survival-stage demand" },
      metrics: {
        marketVolumeMmUsd: 61815,
        perCapitaGdpKUsd: 3.2,
        gdpGrowthPct: 5.8,
        populationK: 36362,
        consumerExpPerCapitaKUsd: 1.7,
        medianAge: 28.0,
        householdSize: 5.2,
        gini: 41.1,
        easeBiz: 69,
      },
      consumption: {
        food: 46,
        clothing: 7,
        housing: 8,
        transport: 13,
        householdComms: 9,
        health: 4,
        education: 2,
        leisure: 2,
        hotelsCatering: 4,
        other: 4,
      },
      narrative: {
        zh: "乌兹别克斯坦市场体量相对有限但增速快；人口年轻、家庭规模大，适合以家庭为单位的品类渗透逻辑。支出高度集中于食品饮料与基础品类，呈现典型生存阶段结构；与哈萨克斯坦相比更偏早期扩张。",
        en: "Uzbekistan is a smaller but fast-growing market—very young and with large households, supporting family-unit categories. Spending is heavily concentrated in food & staples (survival-stage) versus Kazakhstan’s richer-but-still-staples-heavy profile.",
      },
      bullets: {
        zh: ["高增速 + 小市场体量的组合", "大家庭规模：家庭场景需求", "食品饮料占比显著"],
        en: ["Fast growth on a smaller base", "Large households: family-led demand", "Very high food & beverages share"],
      },
      links: [
        { zh: "世界银行｜乌兹别克斯坦", en: "World Bank | Uzbekistan", url: "https://data.worldbank.org/country/uzbekistan" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/UZB" },
        { zh: "乌兹别克斯坦统计局", en: "Statistics Agency", url: "https://stat.uz/en/" },
      ],
    },
    {
      slug: "kazakhstan",
      iso3: "KAZ",
      coords: [48.02, 66.92],
      name: { zh: "哈萨克斯坦", en: "Kazakhstan" },
      region: { zh: "中亚", en: "Central Asia" },
      stage: { zh: "生存需求阶段（结构与发展水平错位）", en: "Survival-stage demand (structure vs. income gap)" },
      metrics: {
        marketVolumeMmUsd: 144245,
        perCapitaGdpKUsd: 14.3,
        gdpGrowthPct: 3.0,
        populationK: 20034,
        consumerExpPerCapitaKUsd: 7.2,
        medianAge: 30.9,
        householdSize: 3.4,
        gini: 29.0,
        easeBiz: 25,
      },
      consumption: {
        food: 51,
        clothing: 8,
        housing: 6,
        transport: 7,
        householdComms: 9,
        health: 5,
        education: 2,
        leisure: 2,
        hotelsCatering: 3,
        other: 5,
      },
      narrative: {
        zh: "哈萨克斯坦人均 GDP 显著高于乌兹别克斯坦，资源部门支撑宏观账面水平；但消费者支出仍高度集中在食品饮料与基础品类。研究指出农产品供给与价格因素可能强化“生存型”结构，形成发展水平与需求阶段的错位，需要在投资假设中单独校验。",
        en: "Kazakhstan is far richer in GDP per capita—commodities anchor macro wealth—yet household baskets remain staples-heavy. The study flags supply/pricing dynamics that can keep survival-stage shares elevated despite incomes, creating a structural disconnect worth stress-testing.",
      },
      bullets: {
        zh: ["高人均 GDP 与生存型支出并存", "食品饮料 + 服饰合计占比高", "能源依赖型增长的宏观背景"],
        en: ["High GDP per capita alongside staples-heavy baskets", "Large food + apparel combined share", "Resource-led macro context"],
      },
      links: [
        { zh: "世界银行｜哈萨克斯坦", en: "World Bank | Kazakhstan", url: "https://data.worldbank.org/country/kazakhstan" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/KAZ" },
        { zh: "哈萨克斯坦统计局 Bureau", en: "Bureau of National Statistics", url: "https://stat.gov.kz/" },
      ],
    },
    {
      slug: "brazil",
      iso3: "BRA",
      coords: [-14.24, -51.93],
      name: { zh: "巴西", en: "Brazil" },
      region: { zh: "拉美", en: "Latin America" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 1350214,
        perCapitaGdpKUsd: 10.3,
        gdpGrowthPct: 2.0,
        populationK: 210971,
        consumerExpPerCapitaKUsd: 6.4,
        medianAge: 35.3,
        householdSize: 2.8,
        gini: 52.0,
        easeBiz: 124,
      },
      consumption: {
        food: 16,
        clothing: 5,
        housing: 16,
        transport: 19,
        householdComms: 11,
        health: 10,
        education: 4,
        leisure: 9,
        hotelsCatering: 5,
        other: 5,
      },
      narrative: {
        zh: "巴西在样本中市场体量最大：人口超过两亿，支出结构整体处于便利阶段并向品质延伸。交通、家居通信与医疗占比相对均衡抬升，反映城市化与服务业渗透；基尼系数与营商环境复杂性提示需求分层与交付摩擦并存。",
        en: "Brazil is the largest consumer market in the set—over 200 million people—with a convenience-stage basket leaning toward transport, household/communications, and healthcare. High inequality and complex regulation imply stratified demand and execution risk.",
      },
      bullets: {
        zh: ["第一大消费市场体量（研究样本内）", "交通 / 家居通信 / 医疗链条占比提升", "不平等与监管复杂度显著"],
        en: ["Largest market size in the sample", "Transport / household-comms / health clusters matter", "Inequality & regulatory complexity"],
      },
      links: [
        { zh: "世界银行｜巴西", en: "World Bank | Brazil", url: "https://data.worldbank.org/country/brazil" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/BRA" },
        { zh: "巴西地理统计局 IBGE", en: "IBGE", url: "https://www.ibge.gov.br/en" },
      ],
    },
    {
      slug: "mexico",
      iso3: "MEX",
      coords: [23.63, -102.55],
      name: { zh: "墨西哥", en: "Mexico" },
      region: { zh: "拉美", en: "Latin America" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 1323889,
        perCapitaGdpKUsd: 14.3,
        gdpGrowthPct: 0.9,
        populationK: 129793,
        consumerExpPerCapitaKUsd: 10.2,
        medianAge: 29.8,
        householdSize: 3.5,
        gini: 42.2,
        easeBiz: 60,
      },
      consumption: {
        food: 26,
        clothing: 2,
        housing: 16,
        transport: 20,
        householdComms: 8,
        health: 3,
        education: 1,
        leisure: 5,
        hotelsCatering: 6,
        other: 11,
      },
      narrative: {
        zh: "墨西哥与巴西同属大体量、相对成熟市场；人口更年轻、不平等低于巴西样本读数。支出结构呈便利型：交通占比较高，“其他”类亦不低，反映多元可选消费与金融服务等混合项；宏观增速温和制约总量弹性预期。",
        en: "Mexico mirrors Brazil in scale and relative maturity but is younger with somewhat lower inequality in the study’s indicators. The basket is convenience-led—transport is high and “other” is chunky (mixed discretionary & services). Modest growth caps headline momentum.",
      },
      bullets: {
        zh: ["拉美第二大经济体量（消费坐标）", "年轻人口 vs 低增速", "交通与广义可选支出权重高"],
        en: ["Large Latin American consumer mass", "Young vs low headline growth", "Transport & broad discretionary weight"],
      },
      links: [
        { zh: "世界银行｜墨西哥", en: "World Bank | Mexico", url: "https://data.worldbank.org/country/mexico" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/MEX" },
        { zh: "墨西哥国家统计局 INEGI", en: "INEGI", url: "https://www.inegi.org.mx/default.html" },
      ],
    },
    {
      slug: "egypt",
      iso3: "EGY",
      coords: [26.82, 30.8],
      name: { zh: "埃及", en: "Egypt" },
      region: { zh: "非洲", en: "Africa" },
      stage: { zh: "生存需求阶段", en: "Survival-stage demand" },
      metrics: {
        marketVolumeMmUsd: 275340,
        perCapitaGdpKUsd: 2.9,
        gdpGrowthPct: 4.2,
        populationK: 105900,
        consumerExpPerCapitaKUsd: 2.6,
        medianAge: 25.8,
        householdSize: 4.0,
        gini: 37.6,
        easeBiz: 114,
      },
      consumption: {
        food: 37,
        clothing: 4,
        housing: 18,
        transport: 6,
        householdComms: 6,
        health: 9,
        education: 4,
        leisure: 2,
        hotelsCatering: 4,
        other: 4,
      },
      narrative: {
        zh: "埃及处于发展初期与高增速区间；人口年轻，住房支出占比相对突出，与研究中对中东—北非房价与居住成本议题的讨论相呼应。食品饮料主导的生存型篮子显著；营商环境约束需要与行业准入、本地化交付一并评估。",
        en: "Egypt combines early-stage development with comparatively fast growth and a young population. Housing share is elevated—consistent with MENA housing-cost narratives—while food remains dominant (survival-stage). Doing-business constraints deserve bottom-up review alongside sector access.",
      },
      bullets: {
        zh: ["高增速 × 发展初期坐标", "住房分项显著", "医疗占比不低（口径主要为自付支出）"],
        en: ["Fast growth / early-stage coordinates", "Elevated housing share", "Non-trivial health share (out-of-pocket framing)"],
      },
      links: [
        { zh: "世界银行｜埃及", en: "World Bank | Egypt", url: "https://data.worldbank.org/country/egypt" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/EGY" },
        { zh: "埃及中央公共动员与统计局 CAPMAS", en: "CAPMAS", url: "http://www.capmas.gov.eg/" },
      ],
    },
    {
      slug: "kenya",
      iso3: "KEN",
      coords: [-1.29, 36.82],
      name: { zh: "肯尼亚", en: "Kenya" },
      region: { zh: "非洲", en: "Africa" },
      stage: { zh: "生存需求阶段", en: "Survival-stage demand" },
      metrics: {
        marketVolumeMmUsd: 95936,
        perCapitaGdpKUsd: 2.2,
        gdpGrowthPct: 4.6,
        populationK: 56433,
        consumerExpPerCapitaKUsd: 1.7,
        medianAge: 20.8,
        householdSize: 4.0,
        gini: 54.0,
        easeBiz: 56,
      },
      consumption: {
        food: 43,
        clothing: 2,
        housing: 15,
        transport: 15,
        householdComms: 8,
        health: 2,
        education: 4,
        leisure: 1,
        hotelsCatering: 1,
        other: 6,
      },
      narrative: {
        zh: "肯尼亚市场规模较小但增速不低；人口极度年轻，不平等偏高。支出极度集中于食品饮料；居住与交通亦占重要份额，呈现城镇化与移动需求扩张的早期形态。研究提示高基尼系数对应的需求分层需要渠道与定价模型分层。",
        en: "Kenya is smaller but fast-growing with an extremely young median age and high inequality. Staples dominate; housing and transport matter early—urbanisation and mobility. Stratified demand calls for segmented route-to-market thinking.",
      },
      bullets: {
        zh: ["极年轻人口结构", "食品饮料占比最高梯队", "不平等程度高 → 分层市场"],
        en: ["Very young demographics", "Top-tier staples share", "High inequality → layered demand"],
      },
      links: [
        { zh: "世界银行｜肯尼亚", en: "World Bank | Kenya", url: "https://data.worldbank.org/country/kenya" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/KEN" },
        { zh: "肯尼亚国家统计局 KNBS", en: "KNBS", url: "https://www.knbs.or.ke/" },
      ],
    },
    {
      slug: "morocco",
      iso3: "MAR",
      coords: [31.79, -7.09],
      name: { zh: "摩洛哥", en: "Morocco" },
      region: { zh: "非洲", en: "Africa" },
      stage: { zh: "生存—便利交汇", en: "Between survival & convenience" },
      metrics: {
        marketVolumeMmUsd: 99011,
        perCapitaGdpKUsd: 4.1,
        gdpGrowthPct: 1.9,
        populationK: 38081,
        consumerExpPerCapitaKUsd: 2.6,
        medianAge: 30.5,
        householdSize: 4.3,
        gini: 38.3,
        easeBiz: 53,
      },
      consumption: {
        food: 35,
        clothing: 4,
        housing: 22,
        transport: 11,
        householdComms: 7,
        health: 4,
        education: 6,
        leisure: 2,
        hotelsCatering: 2,
        other: 6,
      },
      narrative: {
        zh: "摩洛哥处于发展初期与中增速的分层交界；住房支出占比抬升使其在生存与便利之间呈现过渡色彩。食品饮料仍高，教育与医疗占比温和；对接北非与欧洲价值链的位置亦影响可选消费的波动。",
        en: "Morocco sits between early-stage and medium momentum layers. Housing is comparatively large—bridging survival toward convenience—while staples remain high. Trade links with Europe influence discretionary volatility.",
      },
      bullets: {
        zh: ["住房分项高于多数非洲样本", "过渡型结构：生存 + 便利要素并存", "中增速、中小体量市场"],
        en: ["Elevated housing vs many African peers", "Transitional basket", "Medium growth; mid-small scale"],
      },
      links: [
        { zh: "世界银行｜摩洛哥", en: "World Bank | Morocco", url: "https://data.worldbank.org/country/morocco" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/MAR" },
        { zh: "摩洛哥高级规划委员会 HCP", en: "Haut-Commissariat au Plan", url: "https://www.hcp.ma/" },
      ],
    },
    {
      slug: "south-africa",
      iso3: "ZAF",
      coords: [-30.56, 22.94],
      name: { zh: "南非", en: "South Africa" },
      region: { zh: "非洲", en: "Africa" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 256028,
        perCapitaGdpKUsd: 6.3,
        gdpGrowthPct: 0.3,
        populationK: 64007,
        consumerExpPerCapitaKUsd: 4.0,
        medianAge: 29.5,
        householdSize: 3.0,
        gini: 63.8,
        easeBiz: 84,
      },
      consumption: {
        food: 17,
        clothing: 5,
        housing: 15,
        transport: 17,
        householdComms: 9,
        health: 7,
        education: 4,
        leisure: 6,
        hotelsCatering: 5,
        other: 13,
      },
      narrative: {
        zh: "南非宏观增速极低但不平等极高（基尼系数样本内最高梯队）。支出结构更接近便利阶段：交通、居住与其他广义消费权重抬升。研究提醒区域与社会分层使“单一故事线”难以概括全国需求，投资需下沉到城市圈与收入分层。",
        en: "South Africa posts very low headline growth with extreme inequality (top-end Gini in the set). The basket looks convenience-stage—transport, housing, and broad “other” matter. Stratification makes single-country storytelling fragile; geographies and income tiers diverge.",
      },
      bullets: {
        zh: ["不平等程度极高", "便利型支出结构", "增长乏力约束总量预期"],
        en: ["Extreme inequality", "Convenience-stage structure", "Weak growth caps headline upside"],
      },
      links: [
        { zh: "世界银行｜南非", en: "World Bank | South Africa", url: "https://data.worldbank.org/country/south-africa" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/ZAF" },
        { zh: "南非统计局 Stats SA", en: "Statistics South Africa", url: "http://www.statssa.gov.za/" },
      ],
    },
    {
      slug: "saudi-arabia",
      iso3: "SAU",
      coords: [23.89, 45.08],
      name: { zh: "沙特阿拉伯", en: "Saudi Arabia" },
      region: { zh: "中东", en: "Middle East" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 465960,
        perCapitaGdpKUsd: 30.7,
        gdpGrowthPct: 1.7,
        populationK: 35300,
        consumerExpPerCapitaKUsd: 13.2,
        medianAge: 30.9,
        householdSize: 3.4,
        gini: 39.4,
        easeBiz: 62,
      },
      consumption: {
        food: 21,
        clothing: 4,
        housing: 30,
        transport: 15,
        householdComms: 13,
        health: 1,
        education: 3,
        leisure: 4,
        hotelsCatering: 6,
        other: 4,
      },
      narrative: {
        zh: "沙特人均 GDP 与消费能力在研究样本中居前；住房支出占比显著高于多数国家，与研究关于中东房价与投资性需求的讨论一致。整体处于便利阶段：家居通信与交通权重较高。能源转型与本地化政策亦在重塑可选消费的供给侧。",
        en: "Saudi Arabia combines high GDP per capita with a convenience-stage basket heavily tilted toward housing—consistent with regional housing/investment dynamics—and sizable transport and household/communications. Structural reform agendas reshape consumer supply.",
      },
      bullets: {
        zh: ["高人均收入与高住房支出占比", "便利型结构（家居通信 / 交通）", "改革议程下的消费升级预期"],
        en: ["High incomes; outsized housing share", "Convenience-led clusters", "Reform-driven consumption narratives"],
      },
      links: [
        { zh: "世界银行｜沙特", en: "World Bank | Saudi Arabia", url: "https://data.worldbank.org/country/saudi-arabia" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/SAU" },
        { zh: "沙特统计局 GASTAT", en: "General Authority for Statistics", url: "https://www.stats.gov.sa/en" },
      ],
    },
    {
      slug: "uae",
      iso3: "ARE",
      coords: [23.42, 53.85],
      name: { zh: "阿联酋", en: "United Arab Emirates" },
      region: { zh: "中东", en: "Middle East" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 277230,
        perCapitaGdpKUsd: 48.3,
        gdpGrowthPct: 2.4,
        populationK: 11045,
        consumerExpPerCapitaKUsd: 25.1,
        medianAge: 33.8,
        householdSize: 4.8,
        gini: 40.2,
        easeBiz: 16,
      },
      consumption: {
        food: 11,
        clothing: 5,
        housing: 34,
        transport: 14,
        householdComms: 11,
        health: 2,
        education: 8,
        leisure: 3,
        hotelsCatering: 5,
        other: 6,
      },
      narrative: {
        zh: "阿联酋人均指标样本内领先，营商环境友好；住房支出占比极高，教育占比亦不低，反映外籍人口结构与高品质私立教育需求。整体属便利阶段并向品质服务延伸；人口体量小于沙特但客单价与分层更强。",
        en: "The UAE tops several per-capita indicators with a business-friendly climate. Housing dominates; education is comparatively large—consistent with expatriate demographics and premium private schooling. Smaller population than Saudi but higher spending tiers.",
      },
      bullets: {
        zh: ["超高人均收入与住房占比", "教育与高端服务支出显著", "营商环境评分领先"],
        en: ["Very high incomes; housing-heavy basket", "Education & premium services matter", "Strong ease-of-doing-business readings"],
      },
      links: [
        { zh: "世界银行｜阿联酋", en: "World Bank | UAE", url: "https://data.worldbank.org/country/united-arab-emirates" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/ARE" },
        { zh: "阿联酋联邦竞争力与统计局 FCSC", en: "UAE FCSC", url: "https://fcsc.gov.ae/en/" },
      ],
    },
    {
      slug: "poland",
      iso3: "POL",
      coords: [51.92, 19.15],
      name: { zh: "波兰", en: "Poland" },
      region: { zh: "中东欧", en: "Central & Eastern Europe" },
      stage: { zh: "便利需求阶段", en: "Convenience-stage demand" },
      metrics: {
        marketVolumeMmUsd: 517736,
        perCapitaGdpKUsd: 23.7,
        gdpGrowthPct: 2.9,
        populationK: 38637,
        consumerExpPerCapitaKUsd: 13.4,
        medianAge: 42.8,
        householdSize: 3.0,
        gini: 31.5,
        easeBiz: 40,
      },
      consumption: {
        food: 19,
        clothing: 4,
        housing: 21,
        transport: 13,
        householdComms: 6,
        health: 6,
        education: 1,
        leisure: 6,
        hotelsCatering: 4,
        other: 13,
      },
      narrative: {
        zh: "波兰为中等偏大型消费市场，人均发展水平较高；平均年龄偏大，老龄化议题显著。支出结构属便利阶段并向品质迁移：住房与交通为基础盘，“其他”与娱乐占比不低。研究指向消费升级与老龄化相关的长期赛道并重。",
        en: "Poland is a mid/large European consumer market with high development levels and an ageing median age. The basket is convenience-stage migrating toward quality—housing and transport anchor discretionary mixes; ageing lifts healthcare and Silver-economy narratives.",
      },
      bullets: {
        zh: ["中东欧代表样本：成熟 + 中增速", "老龄化：需求结构的长期变量", "不平等相对温和"],
        en: ["CEE benchmark: mature / medium growth", "Ageing as structural demand driver", "Moderate inequality vs EM peers"],
      },
      links: [
        { zh: "世界银行｜波兰", en: "World Bank | Poland", url: "https://data.worldbank.org/country/poland" },
        { zh: "IMF｜国别页面", en: "IMF | Country Page", url: "https://www.imf.org/en/Countries/POL" },
        { zh: "波兰统计局 GUS", en: "Statistics Poland (GUS)", url: "https://stat.gov.pl/en/" },
      ],
    },
  ],
};
